## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [51]:
import pandas as pd

In [52]:
# loading the dataset
data = pd.read_csv("C:/Users/User/Desktop/pandas/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [53]:
data.groupby("sex")["sex"].count()

sex
Female    10771
Male      21790
Name: sex, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [54]:
data[data["sex"] == "Male"]["age"].mean().round(2)

np.float64(39.43)

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [55]:
(((data["native-country"] == "United-States").mean() * 100).round(2))

np.float64(89.59)

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [56]:
# more than 50K per year
mean_more_slry = data[data["salary"] == ">50K"]["age"].mean()
stdv_more_slry = data[data["salary"] == ">50K"]["age"].std()
print(mean_more_slry, stdv_more_slry)
# less than 50K per year
mean_less_slry = data[data["salary"] == "<=50K"]["age"].mean()
stdv_less_slry = data[data["salary"] == "<=50K"]["age"].std()
print(mean_less_slry, stdv_less_slry)

44.24984058155847 10.519027719851826
36.78373786407767 14.02008849082488

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [57]:
data[data["salary"] == ">50K"]["education"].unique()
#No, it's false, the amount of the salaries don't depend on the higher education, 
# as we can see other education levels in the results (schools, colleges and etc.).

array(['HS-grad', 'Masters', 'Bachelors', 'Some-college', 'Assoc-voc',
       'Doctorate', 'Prof-school', 'Assoc-acdm', '7th-8th', '12th',
       '10th', '11th', '9th', '5th-6th', '1st-4th'], dtype=object)

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [58]:
#descriptive statistics
data.groupby(["race", "sex"])["age"].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

In [59]:
#max male age for Asian-Pac-Islander
data[(data["race"] == "Asian-Pac-Islander") & (data["sex"] == "Male")]["age"].max()

np.int64(90)

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [60]:
males = data[data["sex"] == "Male"].copy()
males["is_married"] = males["marital-status"].str.startswith("Married")

males.groupby("is_married")["salary"].value_counts(normalize=True) * 100

# The proportion of high-earning individuals (>50K) 
# is much higher among married men (44.05%) compared to single men (8.45%).

is_married  salary
False       <=50K     91.550491
            >50K       8.449509
True        <=50K     55.948601
            >50K      44.051399
Name: proportion, dtype: float64

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [61]:
max_hours = data["hours-per-week"].max()
workers = data[data["hours-per-week"] == max_hours]
num_top_workers = len(workers)
prcnt_high_earners = (workers["salary"] == ">50K").mean() * 100

print(f"Max hours per week: {max_hours}")
print(f"Number of people working max hours: {num_top_workers}")
print(f"Percentage of high earners (>50K): {prcnt_high_earners:.2f}%")

Max hours per week: 99
Number of people working max hours: 85
Percentage of high earners (>50K): 29.41%

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [63]:
data["native-country"] = data["native-country"].replace("?", "1_Unknown")
data.pivot_table(
    values="hours-per-week", index="native-country", columns="salary", aggfunc="mean"
).round(2)

salary                      <=50K   >50K
native-country
1_Unknown                   40.16  45.55
Cambodia                    41.42  40.00
Canada                      37.91  45.64
China                       37.38  38.90
Columbia                    38.68  50.00
Cuba                        37.99  42.44
Dominican-Republic          42.34  47.00
Ecuador                     38.04  48.75
El-Salvador                 36.03  45.00
England                     40.48  44.53
France                      41.06  50.75
Germany                     39.14  44.98
Greece                      41.81  50.62
Guatemala                   39.36  36.67
Haiti                       36.33  42.75
Holand-Netherlands          40.00    NaN
Honduras                    34.33  60.00
Hong                        39.14  45.00
Hungary                     31.30  50.00
India                       38.23  46.48
Iran                        41.44  47.50
Ireland                     40.95  48.00
Italy                       39.62  45.40
Jamaica                     38.24  41.10
Japan                       41.00  47.96
Laos                        40.38  40.00
Mexico                      40.00  46.58
Nicaragua                   36.09  37.50
Outlying-US(Guam-USVI-etc)  41.86    NaN
Peru                        35.07  40.00
Philippines                 38.07  43.03
Poland                      38.17  39.00
Portugal                    41.94  41.50
Puerto-Rico                 38.47  39.42
Scotland                    39.44  46.67
South                       40.16  51.44
Taiwan                      33.77  46.80
Thailand                    42.87  58.33
Trinadad&Tobago             37.06  40.00
United-States               38.80  45.51
Vietnam                     37.19  39.20
Yugoslavia                  41.60  49.50

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [64]:
data_age = data.copy()

data_age["AgeGroup"] = pd.cut(
    data_age["age"],
    bins=[16, 35, 70, 101],
    labels=["young", "adult", "retiree"],
    right=False,
)

data_age.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [70]:
data_age[data_age["salary"] == ">50K"].groupby("AgeGroup", observed=False)["salary"].count()

AgeGroup
young      1488
adult      6240
retiree     113
Name: salary, dtype: int64

In [66]:
data_age[data_age["salary"] == ">50K"]["AgeGroup"].mode()[0]

'adult'

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [67]:
data_age["occupation"] = data_age["occupation"].replace("?", "1_Unknown")
data_age.groupby("occupation")["occupation"].count()

occupation
1_Unknown            1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
Name: occupation, dtype: int64

In [68]:
def filter_func(g):
    return (g["age"].mean() <= 40) and (g["hours-per-week"] > 5).all()

filtered_data = data_age.groupby("occupation").filter(filter_func)
print(filtered_data["occupation"].unique())

['Armed-Forces']